name: Convert MISP playbooks and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Convert Notebooks to HTML
        run: |
          mkdir -p output
          jupyter nbconvert --to html misp-playbooks/*.ipynb --output-dir output
          
      - name: List files for debugging
        run: ls -R output
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          keepFiles: true
