name: Update README Links

on:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git pull --rebase origin main

    - name: Debug README content
      run: cat README.md

    - name: Update README references
      run: |
        README_FILE="README.md"
        if [ -f "$README_FILE" ]; then
          sed -i 's|\(misp-playbooks/[^ )]*\)\.ipynb|\1.html|g' "$README_FILE"
        fi

    - name: Stage and commit changes
      run: |
        git add README.md
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update README links to HTML files"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
